refresh:
  fields: {}

dump_page:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: arbor
    path:
      required: true
      example: "/guardians/student-ui/assignments/student-id/12345"
      selector:
        text:
    include_values:
      required: false
      default: false
      selector:
        boolean:
